disabled: false
languageCode: en
languageName: English
weight: 1
title: Camp's garbage
params:
  displayName: EN
  isoCode: en
  rtl: false
  dateFormat: Jan. 2 2006
  logo: Discord anim.gif
  secondaryLogo: frame_00_delay-0.03s.gif
  description: Camp's blog for hosting and sharing various notes and thoughts
    about various stuff. It may serve as a document repository for public
    interest stuff too sometimes. I dunno.
  author:
    links:
      - castopod: https://music.jackle.ca/@listen/links
      - codeberg: https://codeberg.org/campfred
      - github: https://github.com/campfred
      - telegram: https://campfred.t.me
      - discord: https://discordapp.com/users/239771146478813185
      - bluesky: https://bsky.app/profile/camp.jackle.ca
      - vrc: https://vrchat.com/home/user/usr_205175e8-775c-421e-a8f1-ca9b0d000ead
      - furaffinity: https://furaffinity.net/user/campfred
      - lastfm: https://www.last.fm/user/campfred
params.author:
  name: Camp
  image: xmaseve event page 12.profile.png
  headline: I'm not a miracle worker... Well, not always. ✨
  bio: Big nerd jackal from Canada 🇨🇦 who tames 🖥️s and digital ☁️s by day and
    (sometimes) 🔊s, 💡s or 💿s by night.
